"""Read structured athlete_profile fields from Supabase."""
from __future__ import annotations

import logging

from .athlete_memory import get_athlete_memory
from .client import get_supabase, row, rows

logger = logging.getLogger(__name__)


def get_meal_variety_preference(user_id: str) -> str:
    """Return the athlete's meal variety preference ('minimal'/'balanced'/'high'), defaulting to 'balanced'."""
    try:
        sb = get_supabase()
        result = row(
            sb.table("athlete_profile")
            .select("meal_variety_preference")
            .eq("user_id", user_id)
            .maybe_single()
            .execute()
        )
        value = (result or {}).get("meal_variety_preference")
        return value or "balanced"
    except Exception as exc:
        logger.warning("Failed to load meal variety preference for %s: %s", user_id, exc)
        return "balanced"


def get_meal_location_context(user_id: str) -> str:
    """Return a one-line summary of the athlete's country + grocery store access, for biasing
    meal-recommendation ingredients toward what's actually available to them. Empty string if
    neither field is set.
    """
    try:
        sb = get_supabase()
        data = row(
            sb.table("athlete_profile")
            .select("country,grocery_stores_notes")
            .eq("user_id", user_id)
            .maybe_single()
            .execute()
        ) or {}
        country = (data.get("country") or "").strip()
        stores = (data.get("grocery_stores_notes") or "").strip()
        parts = []
        if country:
            parts.append(f"Country: {country}")
        if stores:
            parts.append(f"Store access: {stores}")
        return " | ".join(parts)
    except Exception as exc:
        logger.warning("Failed to load meal location context for %s: %s", user_id, exc)
        return ""


def get_weight_goal_direction(user_id: str) -> str:
    """Return the athlete's weight goal direction ('lose'/'maintain'/'gain'), defaulting to 'maintain'."""
    try:
        sb = get_supabase()
        result = row(
            sb.table("athlete_profile")
            .select("weight_goal_direction")
            .eq("user_id", user_id)
            .maybe_single()
            .execute()
        )
        value = (result or {}).get("weight_goal_direction")
        return value or "maintain"
    except Exception as exc:
        logger.warning("Failed to load weight goal direction for %s: %s", user_id, exc)
        return "maintain"


def get_athlete_language(user_id: str) -> str:
    """Return the athlete's selected language ('en'/'no') from user_settings, defaulting to 'en'.

    Read by the coaching pipeline so LangGraph prompts can instruct the LLM to write
    athlete-facing text (plan rationale, feedback, reports) in the same language the web UI
    is showing — see supabase/migrations/042_user_settings_language.sql.
    """
    try:
        sb = get_supabase()
        result = row(
            sb.table("user_settings")
            .select("language")
            .eq("user_id", user_id)
            .maybe_single()
            .execute()
        )
        value = (result or {}).get("language")
        return value if value in ("en", "no") else "en"
    except Exception as exc:
        logger.warning("Failed to load language setting for %s: %s", user_id, exc)
        return "en"


def get_max_heart_rate_bpm(user_id: str) -> int | None:
    """Return the athlete's configured max heart rate (bpm) from user_settings, or None if unset
    or on error — computed and written in cli/ams.py's _compute_max_heart_rate(). Unlike the
    other getters in this file, there's no sensible default to fall back to, so None means
    "not configured" rather than a placeholder value.
    """
    try:
        sb = get_supabase()
        result = row(
            sb.table("user_settings")
            .select("max_heart_rate_bpm")
            .eq("user_id", user_id)
            .maybe_single()
            .execute()
        )
        return (result or {}).get("max_heart_rate_bpm")
    except Exception as exc:
        logger.warning("Failed to load max heart rate for %s: %s", user_id, exc)
        return None


def get_analysis_context(user_id: str) -> str:
    """Return the athlete's LLM-authored analysis-context narrative (goals, background,
    preferences briefing), generated by the web setup wizard and stored live in Supabase.
    """
    try:
        sb = get_supabase()
        result = row(
            sb.table("athlete_profile")
            .select("generated_analysis_context")
            .eq("user_id", user_id)
            .maybe_single()
            .execute()
        )
        return (result or {}).get("generated_analysis_context") or ""
    except Exception as exc:
        logger.warning("Failed to load analysis context for %s: %s", user_id, exc)
        return ""


def get_recurring_session_requests(user_id: str) -> list[dict]:
    """Return the athlete's structured recurring session requests (e.g. 'long run on Sunday')."""
    try:
        sb = get_supabase()
        result = row(
            sb.table("athlete_profile")
            .select("recurring_session_requests")
            .eq("user_id", user_id)
            .maybe_single()
            .execute()
        )
        return (result or {}).get("recurring_session_requests") or []
    except Exception as exc:
        logger.warning("Failed to load recurring session requests for %s: %s", user_id, exc)
        return []


def get_strength_session_templates(user_id: str) -> list[dict]:
    """Return the athlete's saved strength session template rows (slots A/B/C), sorted by slot
    then display_order. Raw rows — see build_strength_templates_context() for the rendered
    markdown version used in the weekly planner prompt.
    """
    try:
        sb = get_supabase()
        return rows(
            sb.table("strength_session_templates")
            .select("*")
            .eq("user_id", user_id)
            .order("slot")
            .order("display_order")
            .execute()
        )
    except Exception as exc:
        logger.warning("Failed to load strength session templates for %s: %s", user_id, exc)
        return []


def build_strength_templates_context(user_id: str) -> str:
    """Render the athlete's saved strength session templates (slots A/B/C) as read-only markdown
    for the weekly planner prompt — it schedules WHICH dates get which slot, but does not author
    exercise content; that comes from these templates via the deterministic expansion step in
    plan_writer.expand_strength_session_slots(), not from the LLM.
    """
    templates = get_strength_session_templates(user_id)
    if not templates:
        return "No strength session templates saved."

    by_slot: dict[str, list[dict]] = {}
    for t in templates:
        by_slot.setdefault(t["slot"], []).append(t)

    lines = []
    for slot in sorted(by_slot):
        exercises = by_slot[slot]
        lines.append(f"### Slot {slot} — {exercises[0]['slot_name']}")
        for ex in exercises:
            if ex["is_dynamic_bench"]:
                lines.append(f"- {ex['display_name']} (dynamic — sets/reps computed automatically, not fixed)")
            else:
                lines.append(f"- {ex['display_name']}: {ex['sets']}x{ex['reps_min']}-{ex['reps_max']}")
        lines.append("")
    return "\n".join(lines).strip()


_DAY_ORDER = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
_SESSION_TYPE_LABELS = {"run": "Run", "strength": "Strength", "cross": "Cross-train", "other": "Other"}


def build_planning_context(user_id: str) -> str:
    """Deterministically render the operational planning context — hard constraints, recurring
    session requests, and soft preferences — from the athlete's live profile.

    This replaces an earlier design where an LLM was asked to restate these same structured
    fields as prose. That approach lost the deliberate softness/hardness of certain choices (e.g.
    a session-count baseline being read back as a hard cap), so every fact here has exactly one
    correct rendering instead of being left to the model's interpretation.
    """
    try:
        sb = get_supabase()
        profile = row(sb.table("athlete_profile").select("*").eq("user_id", user_id).maybe_single().execute()) or {}
    except Exception as exc:
        logger.warning("Failed to load profile for planning context %s: %s", user_id, exc)
        profile = {}

    lines: list[str] = []

    # ── Hard constraints ────────────────────────────────────────────────────
    lines.append("=== HARD CONSTRAINTS (never violate) ===")

    available_days = profile.get("available_days") or []
    if available_days:
        ordered = [d for d in _DAY_ORDER if d in available_days]
        lines.append(f"- Available days: {', '.join(ordered)}")
    else:
        lines.append("- Available days: not specified — assume any day is usable")

    session_duration_mins = profile.get("session_duration_mins")
    if session_duration_mins and session_duration_mins >= 120:
        lines.append("- Session length: No constraint — coach determines optimal length per session")
    elif session_duration_mins:
        lines.append(f"- Session length: up to {session_duration_mins} minutes")

    gym_access = profile.get("gym_access")
    if gym_access is not None:
        lines.append(f"- Gym access: {'Yes' if gym_access else 'No — home or outdoor only'}")

    if profile.get("equipment_notes"):
        lines.append(f"- Equipment: {profile['equipment_notes']}")
    if profile.get("training_years_strength"):
        lines.append(f"- Strength training experience: {profile['training_years_strength']}")
    one_rms = []
    if profile.get("bench_1rm_kg"):
        one_rms.append(f"bench {profile['bench_1rm_kg']}kg")
    if profile.get("squat_1rm_kg"):
        one_rms.append(f"squat {profile['squat_1rm_kg']}kg")
    if profile.get("deadlift_1rm_kg"):
        one_rms.append(f"deadlift {profile['deadlift_1rm_kg']}kg")
    if one_rms:
        lines.append(f"- Current 1RM benchmarks: {', '.join(one_rms)}")
    if profile.get("schedule_notes"):
        lines.append(f"- Schedule constraints: {profile['schedule_notes']}")
    if profile.get("exercises_to_avoid"):
        lines.append(f"- Exercises to avoid: {profile['exercises_to_avoid']}")
    if profile.get("current_injuries"):
        lines.append(f"- Current injuries: {profile['current_injuries']}")
    if profile.get("injury_history"):
        lines.append(f"- Injury history: {profile['injury_history']}")
    if profile.get("health_notes"):
        lines.append(f"- Other health notes: {profile['health_notes']}")
    if profile.get("indoor_outdoor") == "outdoor_only":
        lines.append("- Cardio location: Outdoor only — no treadmills or indoor cardio machines")

    # ── Recurring session requests ──────────────────────────────────────────
    lines.append("")
    lines.append(
        "=== RECURRING SESSION PATTERN ===\n"
        "WHAT the week contains is the commitment: these session types, at this weekly volume, "
        "in this order. WHICH WEEKDAY each lands on is a PREFERENCE, not part of the session's "
        "identity — weekday placement is a convenience, not a training variable, so you may "
        "shift the pattern off its preferred days when reality calls for it (a missed day, "
        "travel, illness). Relative spacing and order are what must be preserved.\n"
        "Entries marked [FIXED DAY] are the exception — a class, a training partner, a standing "
        "commitment — and must stay on the stated weekday.\n"
        "When the plan has drifted off the preferred days, converge back when it is CHEAP (a "
        "rest day can absorb the difference at no training cost) and let it ride when "
        "re-syncing would cost a real session."
    )
    requests = profile.get("recurring_session_requests") or []
    if requests:
        # State the weekly volume as an explicit number. The preferred-day list alone does NOT
        # convey it: when days were hard pins, three Mon/Wed/Fri entries implicitly forced three
        # strength sessions, but softening them to preferences removed that anchor — and a real
        # check-in then planned 2 strength/week while its own narrative claimed 3. Volume is the
        # commitment; the day is not. Say so in numbers.
        must_by_type: dict[str, int] = {}
        for req in requests:
            if req.get("importance") == "must" and req.get("session_type"):
                must_by_type[req["session_type"]] = must_by_type.get(req["session_type"], 0) + 1
        if must_by_type:
            volume = ", ".join(
                f"{n}x {_SESSION_TYPE_LABELS.get(t, t)}" for t, n in sorted(must_by_type.items())
            )
            lines.append(
                f"WEEKLY VOLUME (hard requirement — every week, including weeks where placement "
                f"drifts off the preferred days): {volume}. Count these before finalizing each "
                "week. Reducing volume requires an explicit stated reason (taper, illness, "
                "injury, or a readiness signal) named in coach_feedback."
            )
            lines.append("")
        for req in requests:
            day = req.get("day_of_week")
            day_label = day.capitalize() if day else "Any day"
            type_label = _SESSION_TYPE_LABELS.get(req.get("session_type"), "Session")
            label = req.get("label") or type_label
            importance = "always include" if req.get("importance") == "must" else "include when possible"
            fixed = req.get("day_flexibility") == "fixed"
            day_part = f"{day_label} [FIXED DAY]" if fixed else f"prefers {day_label}"
            desc = req.get("description")
            desc_part = f' — "{desc}"' if desc else ""
            lines.append(f"- {label} ({type_label}), {day_part}{desc_part} [{importance}]")
    else:
        lines.append("No specific recurring requests.")

    # ── Soft preferences ─────────────────────────────────────────────────────
    lines.append("")
    lines.append("=== SOFT PREFERENCES (weigh these; athlete has not stated they are mandatory) ===")

    # Reconcile against the recurring pattern before stating it. A stale sessions_per_week that
    # undercounts the athlete's own recurring requests puts two contradictory numbers in one
    # prompt — and the model anchors on the smaller one: with "5 baseline" alongside a 7-session
    # pattern, a real check-in planned exactly 5 (2 strength + 3 runs + 2 rest), silently
    # dropping a third of the strength work. The explicit pattern is the more specific signal,
    # so it sets the floor.
    stated_per_week = profile.get("sessions_per_week")
    pattern_per_week = sum(
        1 for r in (profile.get("recurring_session_requests") or [])
        if r.get("importance") == "must" and r.get("session_type")
    )
    sessions_per_week = max(stated_per_week or 0, pattern_per_week) or None
    if sessions_per_week:
        note = ""
        if pattern_per_week and stated_per_week and pattern_per_week > stated_per_week:
            note = (
                f" (the athlete's stated baseline is {stated_per_week}, but their own recurring "
                f"pattern already commits to {pattern_per_week} — the pattern wins)"
            )
        lines.append(
            f"- Current weekly sessions: {sessions_per_week} (a FLOOR, not a cap — expand with "
            f"readiness; never plan fewer without a stated recovery reason){note}"
        )
    if profile.get("training_enjoyments"):
        lines.append(f"- Enjoys: {profile['training_enjoyments']}")
    if profile.get("training_dislikes"):
        lines.append(f"- Dislikes / minimize: {profile['training_dislikes']}")
    if profile.get("preferred_style"):
        lines.append(f"- Training style: {profile['preferred_style']}")

    indoor_outdoor = profile.get("indoor_outdoor")
    if indoor_outdoor == "outdoor_pref":
        lines.append("- Cardio preference: Outdoor by default, indoor acceptable as fallback")
    elif indoor_outdoor == "indoor":
        lines.append("- Cardio preference: Indoor by default (treadmill, rowing machine, gym cardio), outdoor acceptable as fallback")
    # "outdoor_only" is rendered as a hard constraint above, not here.
    # "no_pref" carries no signal — omitted.

    weight_goal_direction = profile.get("weight_goal_direction")
    if weight_goal_direction and weight_goal_direction != "maintain":
        lines.append(f"- Weight goal: {weight_goal_direction}")

    if profile.get("additional_notes"):
        lines.append(f"- Additional notes: {profile['additional_notes']}")

    # ── Learned from past check-ins ──────────────────────────────────────────
    # Confirmed facts the athlete has approved from a check-in comment (see
    # athlete_memory_suggestions / migration 047) — never anything still pending review.
    memory_text = get_athlete_memory(user_id)
    if memory_text:
        lines.append("")
        lines.append("=== LEARNED FROM PAST CHECK-INS (confirmed by athlete) ===")
        lines.append(memory_text.strip())

    return "\n".join(lines)
